name: Test and Release
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_call:
  workflow_dispatch:
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for codecov

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: deno fmt --check
      - run: deno lint

      - name: Run tests, produce coverage
        run: deno task test --coverage

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true

  release:
    name: Release (if relevant)
    runs-on: ubuntu-latest
    needs: ["tests"]
    permissions:
      # https://github.com/semantic-release/semantic-release/issues/2469
      contents: write # create releases
      issues: write # issue comments and labels
      pull-requests: write # ditto
      id-token: write # The OIDC ID token is used for authentication with JSR, codecov, npm with provenance
    steps:
      - run: echo 'The Tests workflow passed'

      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: deno task build:npm

      - run: npm install -D @sebbo2002/semantic-release-jsr conventional-changelog-conventionalcommits

      # We did this already but it seems not everythign was installed for jsr publish?  Let's try.
      - run: deno install
      # @sebbo2002/semantic-release-jsr seems to need it
      - run: echo '{"version":"0.0.1"}' > package.json

      - name: Release if relevant
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
